[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
ffi = true # Enabled to support differential fuzz testing

# Compilation
solc_version = "0.8.16"
optimizer = true
optimizer_runs = 10_000
via_ir = true # @todo Off during dev.

# Testing
block_timestamp = 1_680_220_800 # March 31, 2023 at 00:00 GMT
fuzz = { runs = 10 } # Low runs during dev due to heavy ffi usage.

[rpc_endpoints]
mainnet = "https://rpc.ankr.com/eth"
optimism = "https://rpc.ankr.com/optimism"

[fmt]
line_length = 80
int_types = "short"
number_underscore = "preserve"
ignore = []

# Profile for intense testing
# Run via `FOUNDRY_PROFILE=intense forge t`
[profile.intense]
[profile.intense.fuzz]
runs = 10_000
[profile.intense.invariant]
runs = 10_000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
